---
# Source: app-http-chart-meteofrance/templates/app-ingress.yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-ingress-www-meteofrance-com
spec:
  hosts:
  - www.meteofrance.com
  gateways:
  - gateway-ingress-www-meteofrance-com
  - mesh
  http:        
  - match:
    - uri:
        prefix: "/accueil"
      method:
         regex: (GET|POST|PUT|PATCH|DELETE)
    headers:
      request:
        add:
          requestblocking: enabled
          waf: low
          waf-sqli: enabled
          waf-cmdinjection: enabled
          waf-xss: enabled
          realhost: www.meteofrance.com
          #     set:
          #host: botprotection.default.svc.cluster.local
      response:
        remove:
          - Strict-Transport-Security
          - x-frame-options
        add:
          Strict-Transport-Security: 
          x-frame-options: SAMEORIGIN
        set:
          server: toto
    route:
    - destination:
        host: botprotection.default.svc.cluster.local
        subset: high
        port:
          number: 7777        
  - match:
    - uri:
        prefix: "/"
      method:
         regex: POST
    headers:
      request:
        add:
          requestblocking: enabled
          waf: medium
          waf-sqli: enabled
          waf-cmdinjection: enabled
          waf-xss: disabled
          realhost: www.meteofrance.com
          #     set:
          #host: botprotection.default.svc.cluster.local
      response:
        remove:
          - Strict-Transport-Security
          - x-frame-options
        add:
          Strict-Transport-Security: 
          x-frame-options: SAMEORIGIN
        set:
          server: toto
    route:
    - destination:
        host: botprotection.default.svc.cluster.local
        subset: low
        port:
          number: 7777
